name: Agent - Repeat AI Tests - Assistify Product Owner

on:
  workflow_dispatch:
    inputs:
      openai_api_key:
        description: "OpenAI API key"
        required: true
        default: ""
      rounds:
        description: "Number of Rounds"
        type: number
        required: true
        default: 5
      trello_board_name:
        description: "Name of the Trello board"
        required: true
        default: "Assistify"

jobs:
  run-repeat-integration-tests:
    name: "Repeat Integration tests"
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ github.event.inputs.openai_api_key }}
      # Trello API
      TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
      TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
      TRELLO_BOARD_NAME: ${{ github.event.inputs.trello_board_name }}
      # Agent Project
      ASSISTANT_DESCRIPTION: "Product owner tech insights using AI for Assistify"
      ASSISTANT_NAME: "Assistify - Product Owner"
      DATA_FILE_PREFIX: "Assistify - Product Owner"
      # Run Integration Tests
      RUN_INTEGRATION: true

    defaults:
      run:
        working-directory: ./agents/assistify-product-owner

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install hatch
          hatch env create

      - name: Set number of runs
        id: set-number-of-runs
        run: |
          ROUNDS=${{ inputs.rounds || 5 }}
          echo "::notice::Starting $ROUNDS Runs: number_of_runs=$ROUNDS"
          echo "number_of_runs=$ROUNDS" >> "$GITHUB_OUTPUT"

      - name: Run Integration Tests Multiple Times
        run: hatch run test-repeat
        env:
          TESTS_NUMBER_OF_CHOICES: ${{ steps.set-number-of-runs.outputs.number_of_runs }}
