name: Agent - Build - Concierge

on:
  workflow_dispatch:
    inputs:
      openai_api_key:
        description: "OpenAI API key"
        required: true
        default: ""

jobs:
  run-agent-assistify-concierge-build:
    runs-on: ubuntu-latest

    env:
      # OpenAI API
      OPENAI_API_KEY: ${{ github.event.inputs.openai_api_key }}
      OPENAI_MODEL: "gpt-4o-mini"
      # Trello API
      TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
      TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
      TRELLO_BOARD_NAME: "Assistify"
      # Agent Project
      ASSISTANT_DESCRIPTION: "Concierge AI for Assistify"
      ASSISTANT_NAME: "Assistify - Concierge"
      DATA_FILE_PREFIX: "Assistify - Concierge"

    defaults:
      run:
        working-directory: ./agents/assistify-concierge

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install hatch
          hatch env create

      - name: Run Trello Integration
        run: |
          hatch run trello-extract

      - name: Run Code Extraction (Agent - Assistify Concierge)
        run: |
          hatch run summary .
          mv tmp/assistify-concierge.md data/files/code/assistify-concierge.txt

      - name: Run Code Extraction (Assistify API)
        run: |
          hatch run summary "../../assistify-api"
          mv tmp/assistify-api.md data/files/code/assistify-api.txt

      - name: Run Code Extraction (Assistify UI)
        run: |
          hatch run summary "../../assistify-ui"
          mv tmp/assistify-ui.md data/files/code/assistify-ui.txt

      - name: Run Code Extraction (Assistify GitHub Workflows)
        run: |
          hatch run summary "../../.github/workflows"
          mv tmp/workflows.md data/files/code/assistify-github-workflows.txt

      - name: Run Build Agent Concierge
        run: |
          hatch run build
