name: Continuous Integration

on:
  push:
    branches: ["**"]

jobs:
  tests-api:
    name: "Tests API"
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}

    env:
      # OpenAI API
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: assistify-api

    defaults:
      run:
        working-directory: ./assistify-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.X"

      - name: Install dependencies
        run: |
          python -m pip install hatch
          hatch env create

      - name: Unit tests
        run: |
          hatch run test

  tests-ui:
    name: "Tests UI"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./assistify-ui

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Run tests
        run: |
          yarn upgrade
          yarn test:ci
